### ISSUE TITLE
Conflicting type declarations in GL & GLES3

### ISSUE THREAD

**Issue by 1ace** [KhronosGroup/OpenGL-Registry#162] opened 2018-03-02 17:02 UTC
We just had a [bug report in Mesa](https://bugs.freedesktop.org/show_bug.cgi?id=105328) about conflicting type declarations in GL & GLES3 headers.

The gist of it is:
```
/usr/include/GLES3/gl31.h:77:25: error: conflicting declaration 'typedef khronos_ssize_t GLsizeiptr'
 typedef khronos_ssize_t GLsizeiptr;
                         ^~~~~~~~~~
/usr/include/GL/glext.h:468:19: note: previous declaration as 'typedef ptrdiff_t GLsizeiptr'
 typedef ptrdiff_t GLsizeiptr;
                   ^~~~~~~~~~
```

A quick glance at the two headers reveals many more conflicts.

My first thought is that the generation script should detect these duplicates and move them to a common header, which would be included by all the headers; this could look something like:
```
#if defined(GL_ES_VERSION_2_0) || defined(GL_VERSION_1_5)
typedef khronos_ssize_t GLsizeiptr;
typedef khronos_intptr_t GLintptr;
#endif
```

What are your thoughts?

**Comment by brianpaul** [comment] 2018-03-02 17:20
It might also work to simply include khrplatform.h in glext.h and change the typedefs in the GL_VERSION_1_5 section to read:
typedef khronos_ssize_t GLsizeiptr;
typedef khronos_intptr_t GLintptr;

It appears to be legal C/C++ to have duplicated typedefs.

**Comment by oddhack** [comment] 2018-03-02 20:03
Including khrplatform.h and using that would be the way to do this, but it does introduce a new dependency for people using our GL headers which has never existed previously, and will probably break things for users who just download glext.h, say.

This sort of thing was why I was not eager to support including both headers in the same compilation unit to begin with, since they were never intended for that use and nobody had debugged it.

**Comment by nwnk** [comment] 2018-03-02 21:52
> [...] and will probably break things for users who just download glext.h, say.

This has always struck me as a curious model to support. Do people actually do this, and what problem does it solve?

**Comment by oddhack** [comment] 2018-03-16 12:24
@nwnk the whole point of glext.h in the first place was that Microsoft was never going to update the gl.h they shipped on Windows to include support for vendor extensions. These days it mostly just gets packaged with vendor drivers and Mesa, AFAIK.

**Comment by c0d1f1ed** [comment] 2018-03-27 12:38
I don't think breaking the build for people who only downloaded glext.h would be an actual issue. You simply download khrplatform.h and it's fixed. People developing OpenGL ES apps for the first time also quickly discover that they do need that header as well. It's a non-issue and an implementation detail. Who cares which files <vector> includes itself? Just provide the entire implementation and people will be fine.

On the other hand it is a real issue that gl31.h and glext.h cannot both be included. Likewise gl2.h and glcorearb.h have inconsistencies. These problems can't be fixed by users by downloading a missing piece. Changes to glext.h and glcorearb.h are required to resolve this.

**Comment by pdaniell-nv** [comment] 2018-03-27 20:19
It would be ideal if we can fix these inconsistencies. Is there a PR someone can suggest?

**Comment by oddhack** [comment] 2018-03-28 09:53
If you can propose an approach that is demonstrated not to cause a problem with people #including both Microsoft's gl.h and our glext.h / glcorearb.h, I'll look at it.

But it just wasn't in the goals to support the usages you guys are getting up to. For example, how would you deal with GL_EXT_separate_shader_objects - which due to what was admittedly an error, has incompatible specs and APIs in GL and GLES2? Or GL_KHR_context_flush_control, which has the same functionality through two different APIs? Or the fact that GL_ACTIVE_PROGRAM_EXT has different numeric values? Some of those are admittedly errors that weren't noticed when the extensions were defined - but they're errors we have to live with.

**Comment by c0d1f1ed** [comment] 2018-03-28 16:10
Preliminary proof here: https://swiftshader-review.googlesource.com/18108
It has all sorts of combinations of gl.h + glext.h, gl.h + glcorearb.h, glcorearb.h + gl2.h, gl.h + gl31.h, etc. Has both the driver implementation and sample applications. All compile in 32- or 64-bit, on Windows.

The GL_EXT_separate_shader_objects inconsistency isn't a big problem. The entry functions have different names, it's just the enum that has a different value. So we can have a separate compile unit which includes glcorearb.h and one which includes gl2ext.h, which each implement their respective GL_EXT_separate_shader_objects functions. It appears that the GL_KHR_context_flush_control problem can be solved by including gl2ext.h before glcorearb.h and using the _KHR postfixed enums, or using the non-postfixed enums from GL 4.5, which have the same value.

I understand that historically it wasn't the intention to have GL and GLES implementations coexist (either partially in the form of borrowed extensions, or in their entirety), but that's today's reality. Note for instance that ARB_robustness is written against desktop GL, but it mentions WebGL which is based on GLES. Chrome runs on platforms with either GL or GLES, or both, and I'm sure it's not the only cross-platform application that does this. It has several abstraction layers which each count as a GL(ES) implementation in their own right. But e.g. on Mac we have to use ARB_texture_rectangle, and supporting that through a GLES abstraction becomes a challenge when can't include both GL and GLES headers.

I think there's good merit in solving this upstream (i.e. here at Khronos) to facilitate desktop / mobile protability.

**Comment by c0d1f1ed** [comment] 2018-04-13 18:13
Friendly ping. 97a022c and 340d008 work for me. @1ace can you confirm it fixes your specific case too? @brianpaul is this in line with what you had in mind? @oddhack please have a look.

**Comment by pdaniell-nv** [comment] 2018-04-17 20:03
Assigned to @oddhack to help move this forward.

**Comment by c0d1f1ed** [comment] 2018-05-22 16:01
@oddhack can you have a look at my pull request? Thanks.

**Comment by oddhack** [comment] 2018-05-24 12:54
@c0d1f1ed what is the PR? I see the individual commits, but not what branch / PR they're part of.

**Closed** 2018-05-25 21:02 UTC

**Comment by Dav1dde** [comment] 2018-05-26 15:08
Just a heads up this change may break a lot of 3rd party applications that use the XML. This also means khrplatform is a required dependency for any gl header now. Was this intentional?

I think it would have been better to swap the type based on api, mark the element with an `api=` tag. Or go the macro route similar to `GLhandleARB`.

**Comment by oddhack** [comment] 2018-05-27 09:14
@Dav1dde could you explain the nature of the problem you ran into in enough detail that I can try to reproduce it, and figure out what can be done in the XML? Preferably in a new issue, if you don't mind.

**Comment by Mathias-Fuchs** [comment] 2018-06-04 14:07
I'm a layman and I'm having the issue. What's the easiest way to fix it? Help appreciated.

**Comment by oddhack** [comment] 2018-06-04 14:35
@Mathias-Fuchs what is the issue, exactly?

**Comment by Mathias-Fuchs** [comment] 2018-06-04 14:53
Hi Jon!
Alright, the following is my problem: I try to write code against GLES3,
but the automatically included GLES3/gl3.h is not sufficient, for instance
glVertexPointer is not defined in it.
But when I include GL/gl.h as well, I get the conflict between gl3.h and
glext.h, for instance both try to define GLsizeiptr.
I'm currently trying to #define GL_GLEXT_LEGACY so that gl.h doesn't
include glext.h .
So far, that seems to work but I'm not sure if that's the proposed way to
use GLES3 ??
Best, Mathias

**Comment by c0d1f1ed** [comment] 2018-06-04 19:37
Hi Mathias, welcome to OpenGL ES development! Note that glVertexPointer is not a GLES3 function. You probably want glVertexAttribPointer instead. glVertexPointer is part of GLES1 and legacy desktop OpenGL only. That said, this change does attempt to make it valid to include any of the headers. And FWIW I couldn't replicate any issue with including both GLES3/gl3.h and GL/gl.h, on Windows. Could you describe your setup and the error message in more detail?

**Comment by Mathias-Fuchs** [comment] 2018-06-05 11:42
Hi Jon,
Thanks a lot for the help!
Ok, I'll try to use glVertexAttribPointer instead.
I'm on a debian netbook, using the package libgles2-mesa-dev if that gives
a hint to what might have happened?
Best, Mathias

**Comment by rewolff** [comment] 2018-12-27 17:53
Not sure if this is completely the same problem, but I'm trying to compile openscad on a raspberry pi. I'm getting long lists of errors like this: 
```
/usr/include/GLES3/gl31.h:1517:91: error: ‘void __glewVertexAttribBinding(GLuint, GLuint)’ redeclared as different kind of symbol
 GL_APICALL void GL_APIENTRY glVertexAttribBinding (GLuint attribindex, GLuint bindingindex);
                                                                                           ^
In file included from src/system-gl.h:4:0,
                 from src/QGLView.h:3,
                 from src/QGLView.cc:28:
/usr/include/GL/glew.h:17830:46: note: previous declaration ‘void (* __glewVertexAttribBinding)(GLuint, GLuint)’
 GLEW_FUN_EXPORT PFNGLVERTEXATTRIBBINDINGPROC __glewVertexAttribBinding;
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtGui/qopengl.h:99:0,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qopenglwidget.h:49,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QOpenGLWidget:1,
                 from src/QGLView.h:7,
                 from src/QGLView.cc:28:

```

As a workaround I've disabled all the GL_APICALL  lines in gl31.h. The compilation at least gets further now. 

This is a heads-up: Matthias-Fuchs mentions the definitions with   GLsizeiptr, which I've seen too, but in openscad I'm getting hundreds of collisions on the APICALL lines.
